### ISSUE TITLE
Italic renderer should be changed to <i> to match Editor Recommendations

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-basic-styles#28]
See https://github.com/ckeditor/editor-recommendations/issues/2#issuecomment-243758620.

**Comment by Reinmar** [comment]
Together with making changes in this repo we need to review all other repos (including https://github.com/CKEditor5/ckeditor5.github.io/).

**Comment by ansorensen** [comment]
I wish there were an easy way to change to configure this so we could use <em> for italics. In creating content for display on webpages, <em> is more commonly used for italics, and <i> has come to be used for icons.  To avoid strange icons popping up on our site we either have to write a new plugin (and while this should be be an easy fix, I have yet to find an example that works as is) or make sure we have special styles overriding icon styling for ck-editor content (and that we have a way of distinguishing content that was originally produced by ck-editor from other content).
