### ISSUE TITLE
Editor crashes after applying some styling operations to the word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-basic-styles#46]
## Steps to reproduce
1. Write a word "Test".
2. Select letter "e".
3. Press CTRL +B, then CTRL + I.
4. Select whole word.
5. Press CTRL + B 5 times.
6. Press CTRL + I twice.

## Current result 
- Editor crashes
- While performing step 5, you can notice some strange selections.

## Logs
Logs from console - https://gist.github.com/Mgsy/273f81dc2b9e887438b6ef5ca2cbb62c

## Other informations
OS: Windows 10, Ubuntu 16.04
Release: 0.10.0

**Comment by Reinmar** [comment]
Confirmed. Most likely related to (if not caused by) https://github.com/ckeditor/ckeditor5-engine/issues/922.

**Comment by Reinmar** [comment]
Hm... This is actually not the right repo for this ticket (the error comes from the engine), so I'll merge it into https://github.com/ckeditor/ckeditor5-engine/issues/922 anyway. Let's verify this scenario there.
