### ISSUE TITLE
Underline

### ISSUE THREAD

**Issue by ssougnez** [ckeditor/ckeditor5-basic-styles#51]
Hello,

this question can seem a bit stupid but I was wondering why there is no "underline" button in this package. Is it a specific challenge or were "bold" and "italic" just a test to see if it works?

If it's the later and if I'm able to create an underline command (based on the bold one, it shouldn't be too complicated), is it possible for me to contribute to the project? (Sorry I'm not used to the contributing part of Github).

Thanks

**Comment by szymonkups** [comment]
Hello @ssougnez.
We've created [Editor Recommendations](http://ckeditor.github.io/editor-recommendations/) project where editing features are described in much detail. There is a GitHub repository where discussion on each feature is being made. You can find there a proper explanation why underline feature is not included in this repository: https://github.com/ckeditor/editor-recommendations/issues/4.

**Comment by Reinmar** [comment]
The discussion under Editor Recommendations explains why it's unlikely that we'll add this feature to [standard presets](https://github.com/ckeditor/ckeditor5-presets) and [build(s)](https://github.com/ckeditor?utf8=%E2%9C%93&q=ckeditor5-build-&type=&language=). Basically, the ER project was meant to define how the most typical article editor should look like and the underline feature was (so far) identified as not very important one.

However, this doesn't mean that we don't want to have underline, strike through or sub/sup in basic-styles. We just haven't added them yet. 

We don't have contributing guide yet, so I can't direct you to some resource, but of course, we do accept PRs. You'll need to start from checking how our [development environment works](https://github.com/ckeditor/ckeditor5/wiki/Development-Environment), fork the basic-styles package and prepare a PR.

The underline feature will be a copy of existing styles. And I think that we have the icon prepared somewhere (cc @oleq?).

**Comment by Reinmar** [comment]
BTW, I think that underline and strike through are the last easy to add styles. Sub/sup is a bit trickier because there's a question how should applying one over the other behave. And there's also `<code>` which might not be yet considered during rendering spaces ([`DomConverter`](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/module_engine_viewithdomconverter-DomConverter.html) needs to handle spaces inside it differently than normally).

**Comment by oleq** [comment]
> The underline feature will be a copy of existing styles. And I think that we have the icon prepared somewhere (cc @oleq?).

[Ready and waiting](https://github.com/ckeditor/ckeditor5-core/blob/master/theme/icons/underline.svg).
