### ISSUE TITLE
Inline Code

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-basic-styles#52]
There should be support for inline code markup, outputting the `<code>` HTML element.

**Comment by Reinmar** [comment]
We should also think about adding support for codes in the autoformatter. It'd be awesome if it supported <code>\`code\`</code>.

Another thing is an icon. cc @oleq.

And one last thing is whether all this will work in the engine. We didn't yet check whether preformatted text works for real (although, we anticipated it) and it requires a bit different rendering approach.

**Comment by Reinmar** [comment]
PS. When updating autoformatting, please don't forget to update its docs: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/autoformat.html

**Comment by oleq** [comment]
> Another thing is an icon. cc @oleq.

Ping me again when things become serious here ;-)

**Comment by Reinmar** [comment]
I'm pinging :D This is queued for @pomek to work on.

**Comment by fredck** [comment]
> We didn't yet check whether preformatted text works for real

I would not worry about making it "preformatted" (in the model point of view) right now. A quick implementation that works just like bold and italic would do the job at this stage. A follow-up issue could come if we'll like to make this feature more complex later, so it handles spaces differently.

**Comment by oleq** [comment]
> I'm pinging :D This is queued for @pomek to work on.

@pomek, ping me when you ~start dealing~ get advanced with this issue in your queue ;-)

**Comment by Reinmar** [comment]
> I would not worry about making it "preformatted" (in the model point of view) right now. A quick implementation that works just like bold and italic would do the job at this stage. A follow-up issue could come if we'll like to make this feature more complex later, so it handles spaces differently.

If it will turn out that our space rendering algorithm fails to handle `<code>`, we can indeed disable it for now.

**Comment by fredck** [comment]
Btw, not even GH handles spaces inside inline code... so not sure if we should ever support it.

**Comment by fredck** [comment]
For example, I'm adding 10 spaces inside the quotes here: `code( "          " )`

**Comment by Reinmar** [comment]
LOL... true :D

Anyway, this was taken care of a long time ago, so let's just see if it works.

**Comment by oleq** [comment]
Icon ideas so far: 
![image](https://user-images.githubusercontent.com/1099479/29610510-ac0ea278-87fa-11e7-9c31-bb64ac895d22.png)
![image](https://user-images.githubusercontent.com/1099479/29610519-b52e6e9c-87fa-11e7-9932-27dbea83c91a.png)

**Comment by oleq** [comment]
Some improvements to make them feel more lightweight:
![image](https://user-images.githubusercontent.com/1099479/29611327-6ab083ac-87fd-11e7-99a8-4e229fe0de63.png)

**Comment by fredck** [comment]
I like the `</>` idea... but I prefer even more the GH one, which is just `<>`, as it looks more balanced, visually.

**Comment by oleq** [comment]
Added
![image](https://user-images.githubusercontent.com/1099479/29613562-e0d6cb46-8806-11e7-8e5c-56167608e4a6.png)
in https://github.com/ckeditor/ckeditor5-basic-styles/commit/0e797f32a84a58096c7d6e5c943e1f965240f7bc.
