### ISSUE TITLE
Italic plugin view rendering

### ISSUE THREAD

**Issue by jspeha** [ckeditor/ckeditor5-basic-styles#88]
https://github.com/ckeditor/ckeditor5-basic-styles/blob/master/src/italic/italicediting.js#L19

According to this line (19), the italic plugin should render **em** tag to view, but it actually renders **i** tag .. Is this correct behavior and if not, could it be changed so that the plugin actually renders the **em** that is says it's doing (em over i, because bold plugin uses strong and not b)

**Comment by jodator** [comment]
It looks like a typo in the docs unfortunately as the conversion configuration tells something else: https://github.com/ckeditor/ckeditor5-basic-styles/blob/master/src/italic/italicediting.js#L36.

The feature converts `<em>` to `italic` attribute in the model but it always renders it as `<i>`.

To override this you should create a plugin that will override this behavior, ie like this:
```js
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		plugins: [ ArticlePluginSet, function( editor ) {
			editor.conversion.attributeToElement( {
				model: 'italic',
				view: 'em',
				upcastAlso: [
					'i',
					{
						styles: {
							'font-style': 'italic'
						}
					}
				]
			} );
		} ],
		// rest of the config
	} );
```
